name: Build and deploy project to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_PASSWORD }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/testcicd:latest
